apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090/prometheus
    access: proxy
    isDefault: true
  - name: Loki
    type: loki
    url: http://loki:3100/loki
    access: proxy
  - name: Jaeger
    type: jaeger
    url: http://jaeger-query:16686/jaeger
    access: proxy
